# Use postgres/example user/password credentials
version: '3.1'

services:

  dcs-postgres:
    image: postgres
    container_name: dcs-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passpwd
      POSTGRES_USER: postgres
    ports:
      - 5432:5432

  dcs-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dcs-pgadmin
    restart: always
    depends_on:
      - dcs-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

  